micronaut:
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths:
          - classpath:public
  application:
    name: demo
  security:
    enabled: true
    intercept-url-map:
      - pattern: /**
        http-method: GET
        access:
          - isAnonymous()